// Generated by gencpp from file beginner_tutorials/Position.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_POSITION_H
#define BEGINNER_TUTORIALS_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <beginner_tutorials/Linear.h>
#include <beginner_tutorials/Angular.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : linear()
    , angular()  {
    }
  Position_(const ContainerAllocator& _alloc)
    : linear(_alloc)
    , angular(_alloc)  {
  (void)_alloc;
    }



   typedef  ::beginner_tutorials::Linear_<ContainerAllocator>  _linear_type;
  _linear_type linear;

   typedef  ::beginner_tutorials::Angular_<ContainerAllocator>  _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::beginner_tutorials::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::beginner_tutorials::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::beginner_tutorials::Position > PositionPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/smhhgf/shawn_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3216d061298312bfbf56490a98c5cbca";
  }

  static const char* value(const ::beginner_tutorials::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3216d061298312bfULL;
  static const uint64_t static_value2 = 0xbf56490a98c5cbcaULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Position";
  }

  static const char* value(const ::beginner_tutorials::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Linear linear\n\
Angular angular\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Linear\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Angular\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
";
  }

  static const char* value(const ::beginner_tutorials::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Position_<ContainerAllocator>& v)
  {
    s << indent << "linear: ";
    s << std::endl;
    Printer< ::beginner_tutorials::Linear_<ContainerAllocator> >::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::beginner_tutorials::Angular_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_POSITION_H
